name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Dependencies module Three-Forcegraph-Edge-Path-Bundling
        run: cd three-forcegraph-edge-path-bundling && yarn link && yarn install

      - name: Build and Test module Three-Forcegraph-Edge-Path-Bundling
        run: cd three-forcegraph-edge-path-bundling && yarn run build

      - name: Install Dependencies module Aframe-Forcegraph-Component
        run: cd aframe-forcegraph-component-edge-path-bundling && yarn link three-forcegraph && yarn install

      - name: Build and Test module Aframe-Forcegraph-Component
        run: cd aframe-forcegraph-component-edge-path-bundling && yarn run dist

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: emanum/immersive-edge-path-bundling-demo:latest
